### ISSUE TITLE
Fails when application.yml is empty

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/figaro-js#22]
```javascript
TypeError: Cannot read property 'development' of null
    at read (/Users/chawes/Documents/LaunchPad/dev/uolf-client/node_modules/figaro-js/lib/read.js:1:1135)
    at Object.load (/Users/chawes/Documents/LaunchPad/dev/uolf-client/node_modules/figaro-js/lib/load.js:1:559)
    at loadEnv (/Users/chawes/Documents/LaunchPad/dev/uolf-client/config/env.js:6:10)
    at Object.<anonymous> (/Users/chawes/Documents/LaunchPad/dev/uolf-client/config/webpack.config.development.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by rkillackey** [comment]
@dpikt Thought we fixed this in #20? @chawes13 What version are you using?

**Comment by chawes13** [comment]
1.0.2

**Comment by rkillackey** [comment]
@chawes13 Try upgrading to `1.2.0`

**Comment by chawes13** [comment]
Yep, working as expected now.
